---
- name: example of configionals in ansible
  hosts: all
  become: true
  tasks:
    - name: Install FTP package if the node is Redhat based machine & having major version 7
      yum:
         name: ftp
         state: installd
      when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
...          